#服务提供者
server:
  port: 8001
spring:
  application:
    name: AIGOU-PLAT
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #注册到eureka中
  instance:
    instance-id: aigou-plat-8001.com #为当前服务器添加实例的标识
    prefer-ip-address: true